START = 'START' # necessary symbol tags
EPSILON = 'EPSILON'
# nonterminal symbol tags. Symbols taht are mapped to production rules in grammer
FUNC_DEF = 'FUNC_DEF'
FUNC_CALL = 'FUNC_CALL'
ARGS = 'ARGS'
BODY = 'BODY' # a collection of varying lines of evaluation
ID_LIST = 'ID_LIST' # expressions group by comma
STMT   = 'STMT' # single execution line
EXPR = 'EXPR' # expressions grouped with adders
EXPR_LIST = 'EXPR_LIST' # expressions group by comma
EXPR_OP = 'EXPR_OP'# operation with expression
TERM = 'TERM'       #expressions grouped by multipliers
TERM_OP = 'TERM_OP' # operation with term
FACTOR = 'FACTOR' # basic unit of expression
ARGS = 'ARGS'
#terminal symbol tags
NUM = 'NUM'
AND = 'AND'
OR = 'OR'
NOT = 'NOT'
EQUAL  = 'EQUAL'
LESS = 'LESS'
L_EQUAL = 'L_EQUAL'
GREATER = 'GREATER'
G_EQUAL = 'G_EQUAL'
SUB = 'SUB'
ASSIGN = 'ASSIGN'
MUL = 'MUL'
DIV = 'DIV'
ADD = 'ADD'
L_PAREN = 'L_PAREN'
R_PAREN = 'R_PAREN'
IF = 'IF'
ELSE = 'ELSE'
RETURN = 'RETURN'
DEF = 'DEF'
WHILE = 'WHILE'
ID = 'ID'
STR = 'STR'
COMMA = 'COMMA'
SEMICOLON = 'SEMICOLON'