#!/bin/sh
# tial - Tial Is Another Language 
# 	github.com/138paulmiller/tial
#	Usage - patl [source_file] 
#		No argument defaults to interpret standard input deliminated by newlines
python main.py $@